name: Build Kernel
on:
  push:
    branches: OPlus8T-OOS11-horizon

  workflow_dispatch:

jobs:
  build:
    name: Build Kernel by ${{ github.actor }}
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      kernel-url: https://github.com/Sauvio/libxzr-android_kernel_oneplus_sm8250.git
      kernel-dir: kernel
      branch: oos11-ksu
      config: kebab_defconfig
      arch: arm64
      custom-clang: true
      clang-url: https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/tags/android-12.0.0_r34/clang-r416183b.tar.gz
      gcc-aarch64-url: https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/5c970a204b44b1002fd9cbc954084c03e7bf9008.tar.gz
      gcc-arm-url: https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/326e6d4b31cc8c4e3adcf54672735d6f20a60503.tar.gz
      ksu: true
      ksu-version: v0.7.1
      anykernel3: true
      python-27: true
      disable-lto: true
    steps:
      - id: cleanup
        uses: rokibhasansagar/slimhub_actions@main

      - name: install package
        shell: bash
        run: sudo apt install -y binutils binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi git ccache automake flex lzop bison gperf build-essential zip curl gzip xz-utils zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 lib32ncurses5-dev libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler python3

      - name: use python 2.7
        if: env.python-27 == 'true'
        run: |
          sudo apt install -y -q python2.7 python2.7-minimal
          sudo rm /bin/python
          sudo ln -s /bin/python2.7 /bin/python
          sudo ln -s /bin/python2.7 /bin/python2
        shell: bash

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check Environment
        run: |
          echo "RUNNER_OS: $RUNNER_OS"
          echo "RUNNER_TEMP: $RUNNER_TEMP"

      - name: Check glibc Version
        run: ldd --version

      - name: download custom clang
        if: env.custom-clang == 'true'
        run: |
          OUTPUT_FILE="custom-clang.tar.gz"
          CLANG_DIR="$HOME/clang"
          GCC_64="$HOME/gcc-64"
          GCC_32="$HOME/gcc-32"
          mkdir "$CLANG_DIR" -p -v
          mkdir "$GCC_64" -p -v
          mkdir "$GCC_32" -p -v

          # if gcc-aarch64-url && gcc-arm-url exists
          if [ -n "${{ env.gcc-aarch64-url  }}" ] && [ -n "${{ env.gcc-arm-url }}" ]; then
            wget -q "${{ env.gcc-aarch64-url }}" -O gcc-aarch64.tar.gz
            wget -q "${{ env.gcc-arm-url }}" -O gcc-arm.tar.gz

            if tar -tf gcc-aarch64.tar.gz &> /dev/null; then
              tar -xf gcc-aarch64.tar.gz -C "$GCC_64"
            elif file gcc-aarch64.tar.gz | grep -q "gzip compressed data"; then
              tar -xzf gcc-aarch64.tar.gz -C "$GCC_64"
            elif file gcc-aarch64.tar.gz | grep -q "XZ compressed data"; then
              tar -xf gcc-aarch64.tar.gz -C "$GCC_64"
            else
              echo "Unknown compression format or unsupported file"
            fi

            if tar -tf gcc-arm.tar.gz &> /dev/null; then
              tar -xf gcc-arm.tar.gz -C "$GCC_32"
            elif file gcc-arm.tar.gz | grep -q "gzip compressed data"; then
              tar -xzf gcc-arm.tar.gz -C "$GCC_32"
            elif file gcc-arm.tar.gz | grep -q "XZ compressed data"; then
              tar -xf gcc-arm.tar.gz -C "$GCC_32"
            else
              echo "Unknown compression format or unsupported file"
            fi
          fi

          # get clang
          wget -q "${{ env.clang-url}}" -O $OUTPUT_FILE
          if tar -tf $OUTPUT_FILE &> /dev/null; then
            tar -xf $OUTPUT_FILE -C "$CLANG_DIR"
          elif file $OUTPUT_FILE | grep -q "gzip compressed data"; then
            tar -xzf $OUTPUT_FILE -C "$CLANG_DIR"
          elif file $OUTPUT_FILE | grep -q "XZ compressed data"; then
            tar -xf $OUTPUT_FILE -C "$CLANG_DIR"
          else
            echo "Unknown compression format or unsupported file"
          fi

          # Print the content of directories to verify
          echo -e "CLANG_DIR:\n"
          ls -l "$CLANG_DIR"
          echo -e "GCC_64:\n"
          ls -l "$GCC_64"
          echo -e "GCC_32:\n"
          ls -l "$GCC_32"

          # Print Clang version information
          "$CLANG_DIR/bin/clang" --version
        shell: bash

      - name: pull kernel source from selected branch
        run: |
          git clone ${{ env.kernel-url }} -b "${{ env.branch }}" --depth=1 ${{ env.kernel-dir }}
          cd ${{ env.kernel-dir }}
          git submodule init
          git submodule update
        shell: bash

      - name: Setup ccache
        if: env.ccache == 'true'
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: build-kernel-${{ env.arch }}${{ env.config }}
          max-size: 4G

      - name: Set swap space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 12

      - name: pull kernelsu
        if: env.ksu == 'true'
        run: |
          cd ${{ env.kernel-dir }}
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s ${{ env.ksu-version }}
        shell: bash

      - name: disable lto
        if: env.disable-lto == 'true'
        shell: bash
        run: |
          cd ${{ env.kernel-dir }}
          if grep -q "LTO" "arch/${{ env.arch }}/configs/${{ env.config }}"
          then
               sed -i 's/CONFIG_LTO=y/CONFIG_LTO=n/' arch/${{ env.arch }}/configs/${{ env.config }}
               sed -i 's/CONFIG_LTO_CLANG=y/CONFIG_LTO_CLANG=n/' arch/${{ env.arch }}/configs/${{ env.config }}
               sed -i 's/CONFIG_THINLTO=y/CONFIG_THINLTO=n/' arch/${{ env.arch }}/configs/${{ env.config }}
               echo "CONFIG_LTO_NONE=y" >> arch/${{ env.arch }}/configs/${{ env.config }}
          fi

      - name: build kernel with clang
        if: env.custom-clang == 'true'
        run: |
          cd ${{ env.kernel-dir }}
          mkdir -p -v out
          export CLANG_DIR=$HOME/clang
          export PATH=$CLANG_DIR/bin:$PATH
          GCC_64="$HOME/gcc-64"
          GCC_32="$HOME/gcc-32"
          make -j$(nproc --all) \
               CROSS_COMPILE=${GCC_64}/bin/aarch64-linux-android- \
               COMPILE_ARM32=${GCC_32}/bin/arm-linux-androideabi- \
               CLANG_TRIPLE=aarch64-linux-gnu- \
               CC=${CLANG_DIR}/bin/clang \
               ARCH=${{ env.arch }} \
               AR=${CLANG_DIR}/bin/llvm-ar \
               NM=${CLANG_DIR}/bin/llvm-nm \
               LLVM_AR=${CLANG_DIR}/bin/llvm-ar \
               LLVM_NM=${CLANG_DIR}/bin/llvm-nm \
               OBJCOPY=${CLANG_DIR}/bin/llvm-objcopy \
               OBJDUMP=${CLANG_DIR}/bin/llvm-objdump \
               STRIP=${CLANG_DIR}/bin/llvm-strip \
               LD=${CLANG_DIR}/bin/ld.lld \
               O=out \
               ${{ env.config }}
          if [ ${{ env.ccache }} = true ]; then
              export USE_CCACHE=1
              make -j$(nproc --all) \
                   CROSS_COMPILE=${GCC_64}/bin/aarch64-linux-android- \
                   COMPILE_ARM32=${GCC_32}/bin/arm-linux-androideabi- \
                   CLANG_TRIPLE=aarch64-linux-gnu- \
                   CC="ccache ${CLANG_DIR}/bin/clang" \
                   ARCH=${{ env.arch }} \
                   AR=${CLANG_DIR}/bin/llvm-ar \
                   NM=${CLANG_DIR}/bin/llvm-nm \
                   LLVM_AR=${CLANG_DIR}/bin/llvm-ar \
                   LLVM_NM=${CLANG_DIR}/bin/llvm-nm \
                   OBJCOPY=${CLANG_DIR}/bin/llvm-objcopy \
                   OBJDUMP=${CLANG_DIR}/bin/llvm-objdump \
                   STRIP=${CLANG_DIR}/bin/llvm-strip \
                   LD=${CLANG_DIR}/bin/ld.lld \
                   O=out \
                   ${{ env.extra-cmd}}
          else
              make -j$(nproc --all) \
                   CROSS_COMPILE=${GCC_64}/bin/aarch64-linux-android- \
                   COMPILE_ARM32=${GCC_32}/bin/arm-linux-androideabi- \
                   CLANG_TRIPLE=aarch64-linux-gnu- \
                   CC=${CLANG_DIR}/bin/clang \
                   ARCH=${{ env.arch }} \
                   AR=${CLANG_DIR}/bin/llvm-ar \
                   NM=${CLANG_DIR}/bin/llvm-nm \
                   LLVM_AR=${CLANG_DIR}/bin/llvm-ar \
                   LLVM_NM=${CLANG_DIR}/bin/llvm-nm \
                   OBJCOPY=${CLANG_DIR}/bin/llvm-objcopy \
                   OBJDUMP=${CLANG_DIR}/bin/llvm-objdump \
                   STRIP=${CLANG_DIR}/bin/llvm-strip \
                   LD=${CLANG_DIR}/bin/ld.lld \
                   O=out \
                   ${{ env.extra-cmd}}
          fi
        shell: bash

      - name: copy kernel
        if: env.anykernel3 == 'false'
        shell: bash
        run: |
          mkdir -p -v build
          if [ -f ${{ env.kernel-dir }}/out/arch/${{ env.arch }}/boot/Image.*-dtb ]; then
             cp ${{ env.kernel-dir }}/out/arch/${{ env.arch }}/boot/Image.*-dtb build -rv
          elif [ -f ${{ env.kernel-dir }}/out/arch/${{ env.arch }}/boot/Image.* ]; then
             cp ${{ env.kernel-dir }}/out/arch/${{ env.arch }}/boot/Image.* build -rv
          else
             cp ${{ env.kernel-dir }}/out/arch/${{ env.arch }}/boot/Image build -rv
          fi

      - name: package with anykernel3
        if: env.anykernel3 == 'true'
        run: |
          git clone https://github.com/osm0sis/AnyKernel3
          sed -i 's!block=/dev/block/platform/omap/omap_hsmmc.0/by-name/boot;!block=auto;!g' AnyKernel3/anykernel.sh
          sed -i 's/do.devicecheck=1/do.devicecheck=0/g' AnyKernel3/anykernel.sh
          sed -i 's/is_slot_device=0;/is_slot_device=auto;/g' AnyKernel3/anykernel.sh
          echo $(pwd)
          if [ -f ${{ env.kernel-dir }}/out/arch/${{ env.arch }}/boot/Image.*-dtb ]; then
             cp ${{ env.kernel-dir }}/out/arch/${{ env.arch }}/boot/Image.*-dtb AnyKernel3 -rv
          elif [ -f ${{ env.kernel-dir }}/out/arch/${{ env.arch }}/boot/Image.* ]; then
             cp ${{ env.kernel-dir }}/out/arch/${{ env.arch }}/boot/Image.* AnyKernel3 -rv
          else
             cp ${{ env.kernel-dir }}/out/arch/${{ env.arch }}/boot/Image AnyKernel3 -rv
          fi

          test -f ${{ env.kernel-dir }}/out/arch/${{ env.arch }}/boot/dtbo.img && cp ${{ env.kernel-dir }}/out/arch/${{ env.arch }}/boot/dtbo.img AnyKernel3/
          test -f ${{ env.kernel-dir }}/out/arch/${{ env.arch }}/boot/dts/vendor/qcom/kona-v2.1.dtb && cp ${{ env.kernel-dir }}/out/arch/${{ env.arch }}/boot/dts/vendor/qcom/kona-v2.1.dtb AnyKernel3/dtb
          test -f ${{ env.kernel-dir }}/out/arch/${{ env.arch }}/boot/dts/vendor/qcom/instantnoodle-t0.dtb && cp ${{ env.kernel-dir }} /out/arch/${{ env.arch }}/boot/dts/vendor/qcom/instantnoodle-t0.dtb AnyKernel3/dtb
          rm -rf AnyKernel3/.git* AnyKernel3/README.md
        shell: bash

      - id: uploadi
        if: env.anykernel3 == 'false'
        uses: actions/upload-artifact@v3
        with:
          name: bare-compiled-kernel
          path: build/*

      - id: uploada
        if: env.anykernel3 == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: AnyKernel3-flasher
          path: AnyKernel3/*
